---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-java-gateway
  labels:
    app: zabbix
    tier: java
spec:
  selector:
    matchLabels:
     name: zabbix-java-gateway
     app: zabbix
  template:
    metadata:
      labels:
        name: zabbix-java-gateway
        app: zabbix
    spec:
      containers:
        - name: zabbix-java-gateway
          image: zabbix/zabbix-java-gateway:6.0-ol-latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 10052
            protocol: TCP
            name: zabbix-java
          livenessProbe:
            tcpSocket:
              port: 10052
            initialDelaySeconds: 5
            failureThreshold: 3
            periodSeconds: 2
          env:
          - name: ZBX_START_POLLERS
            value: "5"
          - name: ZBX_TIMEOUT
            value: "3"
          - name: ZBX_DEBUGLEVEL
            value: "info"
          - name: JAVA_OPTIONS
            value: ""
          - name: DEBUG_MODE
            value: "false"
          securityContext:
            capabilities: {}
            privileged: false