apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zabbix-app
  namespace: argocd
spec:
  destination:
    namespace: monitoring
    server: https://kubernetes.default.svc
  project: default
  source:
    path: application
    repoURL: https://github.com/Emerson89/zabbix-k8s.git
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true