apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup
  namespace: monitoring
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: mysql
            image: mysql:8.0.19
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - mysqldump zabbix -p$MYSQL_ROOT_PASSWORD > /var/lib/mysql/dump.sql;
            - date; echo Drupal database has been backed up
          restartPolicy: OnFailure