apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize
generatorOptions:
  disableNameSuffixHash: true
namespace: monitoring
resources:
  - namespace.yaml  
  - mysql
  - zabbix-server
  - zabbix-front
secretGenerator:
- name: secrets-agent
  envs:
  - envs/secrets-agent.env
- name: secrets-server
  envs:
  - envs/secrets-server.env
- name: secrets-alertscripts
  files:
  - alertscripts/slack.sh
- name: secrets-externalscripts
  files:
  - externalscripts/monit.py