---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix-server
  template:
    metadata:
      labels:
        app: zabbix-server
    spec:
      containers:
        - name: zabbix-agent
          image: zabbix/zabbix-agent:6.0-ol-latest
          imagePullPolicy: IfNotPresent
          ports:
          - containerPort: 10050
            name: zabbix-agent
          envFrom:
           - secretRef:
               name: secrets-agent  
          env:
          - name: ZBX_HOSTNAME
            value: "Zabbix server"
          - name: ZBX_SERVER_HOST
            value: "127.0.0.1"
          - name: ZBX_PASSIVE_ALLOW
            value: "true"
          - name: ZBX_STARTAGENTS
            value: "3"
          - name: ZBX_TIMEOUT
            value: "10"
          securityContext:
            privileged: true
        - name: zabbix-server
          image: zabbix/zabbix-server-mysql:6.0-ol-latest
          imagePullPolicy: IfNotPresent
          resources:
           requests:
            cpu: 0.1
            memory: 500Mi
          ports:
          - containerPort: 10051
            name: server
            protocol: TCP
          securityContext:  
            privileged: true
          envFrom:
           - secretRef:
               name: secrets-server
           - secretRef:
               name: secrets-alertscripts
           - secretRef:
               name: secrets-externalscripts         
          env:
          - name: DB_SERVER_ROOT_USER
            value: root
          - name: DB_SERVER_HOST
            value: "mysql"
          - name: MYSQL_USER
            value: "zabbix"
          - name: MYSQL_DATABASE
            value: "zabbix"
          - name: ZBX_CACHESIZE
            value: "1024M"
          - name: ZBX_TRENDCACHESIZE
            value: "1024M"
          - name: ZBX_HISTORYCACHESIZE
            value: "2048M"
          - name: ZBX_HISTORYINDEXCACHESIZE
            value: "1024M"
          - name: ZBX_STARTTRAPPERS
            value: "5"
          - name: ZBX_STARTPREPROCESSORS
            value: "10"
          - name: ZBX_STARTDBSYNCERS
            value: "10"
          - name: DB_SERVER_PORT
            value: "3306"
          - name: ZBX_JAVAGATEWAY_ENABLE
            value: "true"
          - name: ZBX_JAVAGATEWAY
            value: "zabbix-java-gateway"
          - name: ZBX_JAVAGATEWAYPORT
            value: "10052"
          - name: ZBX_STARTJAVAPOLLERS
            value: "5"    
          volumeMounts:
            - name: zabbix-alertscripts
              mountPath: /usr/lib/zabbix/alertscripts
            - name: zabbix-externalscripts
              mountPath: /usr/lib/zabbix/externalscripts      
      volumes:
        - name: zabbix-alertscripts
          secret:
           secretName: secrets-alertscripts
           defaultMode: 0755
        - name: zabbix-externalscripts
          secret:
           secretName: secrets-externalscripts
           defaultMode: 0755