---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup
  namespace: monitoring
spec:
  schedule: "1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
             - name: MYSQL_ROOT_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: zabbix-secrets
                   key: MYSQL_ROOT_PASSWORD
             - name: MYSQL_USER
               value: "zabbix"
             - name: MYSQL_DATABASE
               value: "zabbix"
             - name: DB_SERVER_HOST
               value: "mysql"
            image: emr001/alpine-mysql:v1
            imagePullPolicy: IfNotPresent
            name: backup
            command:
             - /bin/sh
             - -c
             - mysqldump -u$MYSQL_USER -p$MYSQL_ROOT_PASSWORD $MYSQL_DATABASE > /root/backup/dump.sql;
             - date; echo Drupal database has been backed up
            volumeMounts:
             - mountPath: /root/backup
               name: mysql-persistent-storage-backup
          volumes:
             - name: mysql-persistent-storage-backup
               persistentVolumeClaim:
                claimName: mysql-pv-claim-backup
          restartPolicy: OnFailure