---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: backup-db-mysql
  namespace: monitoring
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 3
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - env:
             - name: MYSQL_ROOT_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: zabbix-secrets
                   key: MYSQL_ROOT_PASSWORD
             - name: MYSQL_PASSWORD
               valueFrom:
                 secretKeyRef:
                   name: zabbix-secrets
                   key: MYSQL_PASSWORD
             - name: MYSQL_USER
               value: "zabbix"
             - name: MYSQL_DATABASE
               value: "zabbix"
             - name: DB_SERVER_HOST
               value: "mysql"
            image: emr001/alpine-mysql:v1
            imagePullPolicy: IfNotPresent
            name: backup
            command: ["/bin/sh","-c"]
            args:
             - |-
                mysqldump --no-tablespaces -h $DB_SERVER_HOST -u$MYSQL_USER -p$MYSQL_PASSWORD zabbix --single-transaction > /root/backup/zabbix.sql;
                date; echo Backup executado com sucesso...
            volumeMounts:
             - mountPath: /root/backup
               name: mysql-persistent-storage-backup
          volumes:
             - name: mysql-persistent-storage-backup
               persistentVolumeClaim:
                claimName: mysql-pv-claim-backup
          restartPolicy: OnFailure