---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:8.0.19
        name: mysql
        args:
            - "--default-authentication-plugin=mysql_native_password"
            - --character-set-server=utf8
            - --collation-server=utf8_bin
        resources:
          requests:
            cpu: 0.2
            memory: 500Mi
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
          value: "zabbix"
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: zabbix-secrets
              key: MYSQL_PASSWORD
        - name: MYSQL_DATABASE
          value: "zabbix"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
          - name: mysql-config
            mountPath: /etc/mysql/conf.d/
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
          - name: timezone
            mountPath: /etc/localtime
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-config
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/America/Sao_Paulo
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim